import React, { useState } from 'react';
import { GoogleGenAI } from "@google/genai";
import { Image as ImageIcon, Loader2, AlertCircle, Download, Sparkles, RefreshCw } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

export const VisualDemo: React.FC = () => {
  const [status, setStatus] = useState<'idle' | 'generating' | 'success' | 'error'>('idle');
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generateVisual = async () => {
    setStatus('generating');
    setError(null);

    try {
      // Use the environment API key which is pre-configured
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || '' });
      
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              text: 'A cinematic, high-detail visualization of a futuristic digital vault. The aesthetic is "Midnight" with deep purples, dark blues, and glowing cyan accents. In the center, a translucent, crystalline container holds glowing data particles. The surrounding environment is a high-tech sanctuary with geometric patterns and soft ambient lighting. Zero-knowledge proof symbols (mathematical circles and locks) are subtly integrated into the background architecture. 8k resolution, photorealistic, ethereal lighting.',
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9",
          },
        },
      });

      let foundImage = false;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          const base64EncodeString = part.inlineData.data;
          const url = `data:image/png;base64,${base64EncodeString}`;
          setImageUrl(url);
          foundImage = true;
          break;
        }
      }

      if (foundImage) {
        setStatus('success');
      } else {
        throw new Error('No image was generated by the model.');
      }

    } catch (err: any) {
      console.error(err);
      setError(err.message || 'An error occurred during visualization generation.');
      setStatus('error');
    }
  };

  return (
    <div className="bg-midnight-card rounded-[32px] p-8 border border-midnight-purple/30 overflow-hidden relative">
      <div className="flex flex-col items-center text-center space-y-6">
        <div className="w-16 h-16 bg-midnight-cyan/10 rounded-2xl flex items-center justify-center text-midnight-cyan">
          <ImageIcon size={32} />
        </div>
        
        <div>
          <h3 className="text-2xl font-semibold mb-2">AI Concept Visualization</h3>
          <p className="text-gray-400 max-w-md mx-auto">
            Generate a cinematic AI visualization of the Family Heirloom vault. No API key required.
          </p>
        </div>

        <AnimatePresence mode="wait">
          {status === 'idle' && (
            <motion.button
              key="start"
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.9 }}
              onClick={generateVisual}
              className="px-8 py-4 bg-midnight-cyan text-black rounded-2xl font-bold flex items-center gap-3 hover:bg-midnight-cyan/80 transition-all shadow-[0_0_20px_rgba(34,211,238,0.2)]"
            >
              Generate Visualization
              <Sparkles size={20} />
            </motion.button>
          )}

          {status === 'generating' && (
            <motion.div
              key="loading"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center space-y-4"
            >
              <Loader2 className="animate-spin text-midnight-cyan" size={48} />
              <p className="text-midnight-cyan font-mono text-sm animate-pulse">Crafting your cinematic vault...</p>
              <p className="text-xs text-gray-500 italic">This usually takes 10-20 seconds.</p>
            </motion.div>
          )}

          {status === 'success' && imageUrl && (
            <motion.div
              key="success"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="w-full space-y-6"
            >
              <div className="aspect-video rounded-2xl overflow-hidden border border-white/10 bg-black relative group">
                <img 
                  src={imageUrl} 
                  alt="AI Generated Vault Visualization" 
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex items-end p-6">
                  <p className="text-white text-sm font-medium">Family Heirloom: Zero-Knowledge Vault Concept</p>
                </div>
              </div>
              
              <div className="flex justify-center gap-4">
                <button 
                  onClick={() => setStatus('idle')}
                  className="px-6 py-3 bg-white/5 rounded-xl text-sm font-medium hover:bg-white/10 transition-colors flex items-center gap-2"
                >
                  <RefreshCw size={16} />
                  Regenerate
                </button>
                <a 
                  href={imageUrl} 
                  download="family-heirloom-concept.png"
                  className="px-6 py-3 bg-midnight-purple text-white rounded-xl text-sm font-bold flex items-center gap-2 hover:bg-midnight-purple/80 transition-colors"
                >
                  <Download size={16} />
                  Save Concept
                </a>
              </div>
            </motion.div>
          )}

          {status === 'error' && (
            <motion.div
              key="error"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center space-y-4 p-6 bg-red-500/10 border border-red-500/30 rounded-2xl"
            >
              <AlertCircle className="text-red-500" size={32} />
              <p className="text-red-400 text-sm font-medium">{error}</p>
              <button 
                onClick={generateVisual}
                className="px-6 py-2 bg-red-500 text-white rounded-xl text-sm font-bold hover:bg-red-600 transition-colors"
              >
                Try Again
              </button>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Decorative background elements */}
      <div className="absolute -top-24 -right-24 w-48 h-48 bg-midnight-purple/10 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-24 -left-24 w-48 h-48 bg-midnight-cyan/10 rounded-full blur-3xl pointer-events-none" />
    </div>
  );
};
